export const defaultBooks = [
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/p2d9mS3/a36832000f6be243a78f1704827bffe9.jpg",
    name: "Computer Programming",
    author: "Tamim Shahriar Subin",
    price: 220,
    rating: 5,
    publishYear: 2015,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/0jnGD1J/e53af8191-202772.png",
    name: "Haate Kolome Javascript",
    author: "Junayed Ahmed",
    price: 230,
    rating: 4,
    publishYear: 2021,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/wrtQhWS/9788172234980.webp",
    name: "The Alchemist",
    author: "Paulo Coelho",
    price: 290,
    rating: 5,
    publishYear: 1995,
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    photoUrl:
      "https://i.ibb.co/NrHSB95/The-Great-Gatsby-F-Scott-Fitzgerald-efcff-86168.jpg",
    name: "The Great Gatsby",
    author: "F.Sctot Fitzgerald",
    price: 190,
    rating: 3,
    publishYear: 2012,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/84FS3mN/c0e192e5c-53062.jpg",
    name: "The Kite Runner",
    author: "Khaled Hosseini",
    price: 390,
    rating: 4,
    publishYear: 2005,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    photoUrl:
      "https://i.ibb.co/vQj3CFX/The-Prophet-Khalil-Gibran-99624-347587.jpg",
    name: "The Prophet",
    author: "Kahlil Gibran",
    price: 410,
    rating: 5,
    publishYear: 2005,
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/QXXxcfJ/image.jpg",
    name: "Habluder Jonno Programming",
    author: "Jhankar Mahbub",
    price: 250,
    rating: 4,
    publishYear: 2019,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/1QcdgXN/22f81d4bf-90991.jpg",
    name: "Thing and Grow Rich",
    author: "Nepoleon Hill",
    price: 280,
    rating: 4,
    publishYear: 2013,
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    photoUrl:
      "https://i.ibb.co/Cn47RhX/A-Tale-of-Two-Cities-Charles-Dickens-72b65-86448.jpg",
    name: "A Tale of Two Cities",
    author: "Charles Dickens",
    price: 340,
    rating: 5,
    publishYear: 2007,
    isFavourite: false,
  },
];
