export const defaultBooks = [
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/QXXxcfJ/image.jpg",
    name: "Habluder Jonno Programming",
    author: "Jhankar Mahbub",
    price: 250,
    rating: 4,
    publishYear: 2019,
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/p2d9mS3/a36832000f6be243a78f1704827bffe9.jpg",
    name: "Computer Programming",
    author: "Tamim Shahriar Subin",
    price: 220,
    rating: 5,
    publishYear: 2015,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    photoUrl: "https://i.ibb.co/0jnGD1J/e53af8191-202772.png",
    name: "Haate Kolome Javascript",
    author: "Junayed Ahmed",
    price: 230,
    rating: 4,
    publishYear: 2021,
    isFavourite: false,
  },
];
